### ISSUE TITLE
Balance calculation for Battanian and Khuzait speed bonus

### ISSUE THREAD

**Issue by Razorts** [wonkotron/CulturalFeatFixes#2]
Those perks are applied in a wrong way, Battanian one is there to reduce speed penalty in forests so the only thing it should change is forest speed penalty. ie forest penalty -x for batania its
 -x * (1 - bonus)
Khuzait perk is there just for cavalry so in similar way it should modify that portion, would argue it should get bonus for mounted infantry too, ie 
base + cavalry * (1 + bonus) + mounted infantry * (1 + bonus)

**Comment by wonkotron** [comment]
I agree completely, though this is a different class of bug than the one which was originally resolved.  Will fix.
